Loading rhel8/default-amp
  Loading requirement: rhel8/slurm singularity/current rhel8/global cuda/11.4
    libpciaccess/0.16/gcc-9.4.0-6fonbj6 libiconv/1.16/gcc-9.4.0-ahebbov
    libxml2/2.9.12/gcc-9.4.0-gnknt5e ncurses/6.2/gcc-9.4.0-aiirok7
    hwloc/2.5.0/gcc-9.4.0-7sqomga libevent/2.1.12/gcc-9.4.0-hgny7cm
    numactl/2.0.14/gcc-9.4.0-52dwc6n cuda/11.4.0/gcc-9.4.0-3hnxhjt
    gdrcopy/2.2/gcc-9.4.0-e4igtfp knem/1.1.4/gcc-9.4.0-bpbxgva
    libnl/3.3.0/gcc-9.4.0-whwhrwb rdma-core/34.0/gcc-9.4.0-5eo5n2u
    ucx/1.11.1/gcc-9.4.0-lktqyl4 openmpi/4.1.1/gcc-9.4.0-epagguv
/var/spool/slurm/slurmd/job9767968/slurm_script: line 65: conda: command not found
Changed directory to /rds/user/ana42/hpc-work/sae_entities.

JobID: 9767968
======
Time: Thu May 22 17:22:49 BST 2025
Running on master node: gpu-q-3
Current directory: /rds/user/ana42/hpc-work/sae_entities

Nodes allocated:
================
gpu-q-3

numtasks=1, numnodes=1, mpi_tasks_per_node=1 (OMP_NUM_THREADS=1)

Executing command:
==================
python -u test_gemma_2_2b.py  > logs/out.9767968

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:45<01:31, 45.76s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:31<00:45, 45.48s/it]Loading checkpoint shards: 100%|██████████| 3/3 [01:35<00:00, 26.68s/it]Loading checkpoint shards: 100%|██████████| 3/3 [01:35<00:00, 31.78s/it]
/rds/user/ana42/hpc-work/sae_entities/.venv/lib64/python3.11/site-packages/transformers/generation/configuration_utils.py:629: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
Traceback (most recent call last):
  File "/rds/user/ana42/hpc-work/sae_entities/test_gemma_2_2b.py", line 184, in <module>
    generate_prompts("gender_1")
  File "/rds/user/ana42/hpc-work/sae_entities/test_gemma_2_2b.py", line 179, in generate_prompts
    with open(f".z_data/generated_data/generated_{attribute_cat}_bias_data_updated.json", "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.z_data/generated_data/generated_gender_1_bias_data_updated.json'
